---
title: "Template_Keras_Regression_Carseats"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction
The main idea is to try out the deep learning nueral network to improve the prediction accuracy

# Data set
The data set comes from ISLR package
Reference for converting data
https://cran.r-project.org/web/packages/fastDummies/vignettes/making-dummy-variables.html
```{r message=FALSE}
library(keras)
library(ISLR)
```
## Construct training and testing data sets
```{r}
data <- Carseats
head(data)
```
```{r}
set.seed(123)
# randomly order the dataset
rows<-sample(nrow(data))
data<-data[rows, ]
head(data) # pay attention to the row index
```
```{r}
library(fastDummies)
data_cat <- dummy_columns(data) 
names(data_cat)
```
```{r}
# check structure
str(data_cat)
```
```{r}
# remove original categorical predictors

data_clean <- subset(data_cat, select = -c(ShelveLoc, Urban, US))
```


```{r}
# to split the data into train / test sub data sets of 70% vs 30% ratio
split <- round(nrow(data_clean)*0.7)
```

```{r}
# reform the dataset to interface with Keras
# first column is 'Sales'
train_data <- data_clean[1:split, -1]
train_targets<-data_clean[1:split, 1]

test_data <- data_clean[(split+1):nrow(data_clean), -1]
test_targets <- data_clean[(split+1):nrow(data_clean), 1]
```
```{r}
# converted to matrix
train_data<-as.matrix(train_data)
train_targets<-as.matrix(train_targets)

#converted to matrix
test_data<-as.matrix(test_data)
test_targets<-as.matrix(test_targets)
```
```{r}
#scale the data sets for the neural network model
mean <- apply(train_data, 2, mean)
std <- apply(train_data, 2, sd)
train_data <- scale(train_data, center = mean, scale = std)
test_data <- scale(test_data, center = mean, scale = std)
```
```{r}
# to construct the model as a 'function'
build_model <- function() {
  model <- keras_model_sequential() %>% 
    layer_dense(units = 50, activation = "relu", 
                input_shape = dim(train_data)[[2]]) %>% 
    layer_dense(units = 50, activation = "relu") %>% 
    layer_dense(units = 1) 
  
  model %>% compile(
    optimizer = "rmsprop", 
    loss = "mse", 
    metrics = c("mae")
  )
}
```
```{r}
## Due to small data set, K-fold validation is used
k <- 4
indices <- sample(1:nrow(train_data))
folds <- cut(1:length(indices), breaks = k, labels = FALSE) 
num_epochs <- 100
all_scores <- c()
for (i in 1:k) {
  cat("processing fold #", i, "\n")
  # Prepare the validation data: data from partition # k
  val_indices <- which(folds == i, arr.ind = TRUE) 
  val_data <- train_data[val_indices,]
  val_targets <- train_targets[val_indices]
  
  # Prepare the training data: data from all other partitions
  partial_train_data <- train_data[-val_indices,]
  partial_train_targets <- train_targets[-val_indices]
  
  # Build the Keras model (already compiled)
  model <- build_model()
  
  # Train the model (in silent mode, verbose=0)
  model %>% fit(partial_train_data, partial_train_targets,
                epochs = num_epochs, batch_size = 1, verbose = 0)
  
  # Evaluate the model on the validation data
  results <- model %>% evaluate(val_data, val_targets, verbose = 0)
  all_scores <- c(all_scores, results$mean_absolute_error)
}  
all_scores
mean(all_scores)
```
```{r}
# memory clean-up
k_clear_session()
```
```{r}
num_epochs <- 200
all_mae_histories <- NULL
for (i in 1:k) {
  cat("processing fold #", i, "\n")
  
  # Prepare the validation data: data from partition # k
  val_indices <- which(folds == i, arr.ind = TRUE)
  val_data <- train_data[val_indices,]
  val_targets <- train_targets[val_indices]
  
  # Prepare the training data: data from all other partitions
  partial_train_data <- train_data[-val_indices,]
  partial_train_targets <- train_targets[-val_indices]
  
  # Build the Keras model (already compiled)
  model <- build_model()
  
  # Train the model (in silent mode, verbose=0)
  history <- model %>% fit(
    partial_train_data, partial_train_targets,
    validation_data = list(val_data, val_targets),
    epochs = num_epochs, batch_size = 1, verbose = 0
  )
  mae_history <- history$metrics$val_mean_absolute_error
  all_mae_histories <- rbind(all_mae_histories, mae_history)
  
}
```
```{r}
# compute the average of the per-epoch MAE scores for all folds:
average_mae_history <- data.frame(
  epoch = seq(1:ncol(all_mae_histories)),
  validation_mae = apply(all_mae_histories, 2, mean)
)
```

```{r}
library(ggplot2)
# plot the validation mae
ggplot(average_mae_history, aes(x = epoch, y = validation_mae)) + geom_line()
```
```{r}
# plot it with geom_smooth fashion
ggplot(average_mae_history, aes(x = epoch, y = validation_mae)) + geom_smooth()
```
```{r}
# Get a fresh, compiled model based on 'optimal' epoch
model <- build_model()
# Train it on the entirety of the data.
model %>% fit(train_data, train_targets,
              epochs = 20, batch_size = 1, verbose = 0)
result <- model %>% evaluate(test_data, test_targets)
```
```{r}
#print out result
result
```
```{r}
# get the 'predicted' ozone values and compare it against 'true' values
test_pred <- model %>% predict(test_data)
qplot(x=test_targets, y=test_pred, xlim = c(0, 20), ylim = c(0, 20)) +
  geom_abline(intercept = 0, slope = 1, color="blue", size=0.5)
  
# abline(0,1, col="black")
```



